export type Person = {
    firstName: string;
    lastName: string;
    city: string;
    disabled : Boolean;
  };
  
  export const data = [
    {
      id:1,
      days:'Monday',
      clock:'09:00',
      time:'20d',
      tbv:'5d',
      nameSurname:'Celal Abdullatif',
      type:'Doctor',
      typeId:1,
      category:'A',
      spec:'URO',
      pot:'13%',
      connected:'İstinye Üniversitesi Medical Park',
      connectedId:1,
      disabled:false
    },
    {
      id:2,
      days:'Monday',
      clock:'09:25',
      time:'20d',
      tbv:'5d',
      nameSurname:'Metehan Abdullatif',
      type:'Pharmacy',
      typeId:2,
      category:'B',
      spec:'URO',
      pot:'13%',
      connected:'Medicana',
      connectedId:2,
      disabled:false
    },
    {
      id:3,
      days:'Monday',
      clock:'09:50',
      time:'20d',
      tbv:'5d',
      nameSurname:'Ali Abdullatif',
      type:'Doctor',
      typeId:1,
      category:'C',
      spec:'URO',
      pot:'13%',
      connected:'İstinye Üniversitesi Medical Park',
      connectedId:1,
      disabled:false
    },
    {
      id:4,
      days:'Monday',
      clock:'10:15',
      time:'20d',
      tbv:'5d',
      nameSurname:'Osman Abdullatif',
      type:'Doctor',
      typeId:1,
      category:'A',
      spec:'URO',
      pot:'13%',
      connected:'İstinye Üniversitesi Medical Park',
      connectedId:1,
      disabled:false
    },
    {
      id:5,
      days:'Monday',
      clock:'10:40',
      time:'20d',
      tbv:'5d',
      nameSurname:'Furkan Abdullatif',
      type:'Doctor',
      typeId:1,
      category:'A',
      spec:'URO',
      pot:'13%',
      connected:'İstinye Üniversitesi Medical Park',
      connectedId:1,
      disabled:false
    },
    {
      id:6,
      days:'Monday',
      clock:'11:05',
      time:'20d',
      tbv:'5d',
      nameSurname:'Mükerrem Zeynep',
      type:'Doctor',
      typeId:1,
      category:'A',
      spec:'CAR',
      pot:'13%',
      connected:'İstinye Üniversitesi Medical Park',
      connectedId:1,
      disabled:false
    },
    {
      id:7,
      days:'Monday',
      clock:'11:30',
      time:'20d',
      tbv:'5d',
      nameSurname:'Bestami Gurur',
      type:'Doctor',
      typeId:1,
      category:'B',
      spec:'CAR',
      pot:'13%',
      connected:'İstinye Üniversitesi Medical Park',
      connectedId:1,
      disabled:false
    },
    {
      id:8,
      days:'Monday',
      clock:'11:55',
      time:'20d',
      tbv:'5d',
      nameSurname:'Aykanat Kısa',
      type:'Doctor',
      typeId:1,
      category:'B',
      spec:'CAR',
      pot:'13%',
      connected:'İstinye Üniversitesi Medical Park',
      connectedId:1,
      disabled:false
    },
    {
      id:9,
      days:'Monday',
      clock:'12:20',
      time:'20d',
      tbv:'5d',
      nameSurname:'Binnur Eczanesi',
      type:'Pharmacy',
      typeId:2,
      category:'A',
      spec:'-',
      pot:'13%',
      connected:'İstinye Üniversitesi Medical Park',
      connectedId:1,
      disabled:false
    },
    {
      id:10,
      days:'Monday',
      clock:'12:45',
      time:'20d',
      tbv:'5d',
      nameSurname:'Derman Eczanesi',
      type:'Pharmacy',
      typeId:2,
      category:'A',
      spec:'-',
      pot:'13%',
      connected:'İstinye Üniversitesi Medical Park',
      connectedId:1,
      disabled:false
    },
    {
      id:11,
      days:'Monday',
      clock:'13:10',
      time:'60d',
      tbv:' ',
      nameSurname:'Launch Time',
      type:' ',
      typeId:' ',
      category:' ',
      spec:'-',
      pot:' ',
      connected:' ',
      connectedId:0,
      disabled:true
    },
    {
      id:12,
      days:'Monday',
      clock:'14:10',
      time:'20d',
      tbv:'5d',
      nameSurname:'Faruk Eczanesi',
      type:'Pharmacy',
      typeId:2,
      category:'A',
      spec:'-',
      pot:'13%',
      connected:'İstinye Üniversitesi Medical Park',
      connectedId:1,
      disabled:false
    },
    {
      id:13,
      days:'Monday',
      clock:'14:35',
      time:'20d',
      tbv:' ',
      nameSurname:'Rami Eczanesi',
      type:'Pharmacy',
      typeId:2,
      category:'C',
      spec:'-',
      pot:'13%',
      connected:'İstinye Üniversitesi Medical Park',
      connectedId:1,
      disabled:false
    },
    {
      id:14,
      days:'Monday',
      clock:'16:00',
      time:'40d',
      tbv:' ',
      nameSurname:'Traveling Time',
      type:' ',
      typeId:' ',
      category:' ',
      spec:'-',
      pot:' ',
      connected:' ',
      connectedId:0,
      disabled:true
    },
    {
      id:15,
      days:'Monday',
      clock:'16:30',
      time:'20d',
      tbv:'5d',
      nameSurname:'Rafi Eryılmaz',
      type:'Doctor',
      typeId:1,
      category:'A',
      spec:'URO',
      pot:'13%',
      connected:'Kanuni Sultan Süleyman Hastanesi',
      connectedId:3,
      disabled:false
    },
    {
      id:16,
      days:'Monday',
      clock:'16:55',
      time:'15d',
      tbv:' ',
      nameSurname:'Report Time',
      type:' ',
      typeId:' ',
      category:' ',
      spec:'-',
      pot:' ',
      connected:' ',
      connectedId:0,
      disabled:true
    },
    {
      id:17,
      days:'Monday',
      clock:'17:10',
      time:'30d',
      tbv:' ',
      nameSurname:'Training Time',
      type:' ',
      typeId:' ',
      category:' ',
      spec:'-',
      pot:' ',
      connected:' ',
      connectedId:0,
      disabled:true
    },
    {
      id:18,
      days:'Monday',
      clock:'17:40',
      time:'30d',
      tbv:' ',
      nameSurname:'Quiz Time',
      type:' ',
      typeId:' ',
      category:' ',
      spec:'-',
      pot:' ',
      connected:' ',
      connectedId:0,
      disabled:true
    },
  ];
  
  export const dataLeft = [
    {
      id:1,
      days:'-',
      clock:'-',
      time:'-',
      tbv:'-',
      nameSurname:'Celal Abdullatif',
      type:'Doctor',
      typeId:1,
      category:'A',
      spec:'URO',
      pot:'13%',
      connected:'İstinye Üniversitesi Medical Park',
      connectedId:1,
      disabled:false
    },
    {
      id:2,
      days:'-',
      clock:'-',
      time:'-',
      tbv:'-',
      nameSurname:'Metehan Abdullatif',
      type:'Pharmacy',
      typeId:2,
      category:'B',
      spec:'URO',
      pot:'13%',
      connected:'Medicana',
      connectedId:2,
      disabled:false
    },
    {
      id:3,
      days:'-',
      clock:'-',
      time:'-',
      tbv:'-',
      nameSurname:'Ali Abdullatif',
      type:'Doctor',
      typeId:1,
      category:'C',
      spec:'URO',
      pot:'13%',
      connected:'İstinye Üniversitesi Medical Park',
      connectedId:1,
      disabled:false
    },
  ]