export const BrochureActionTypes = {
    SET_CONTENT_ID: 'SET_CONTENT_ID',
    CLEAR_CONTENT_ID: 'CLEAR_CONTENT_ID',
    SET_DISADVANTAGE_CONTENT_ID: 'SET_DISADVANTAGE_CONTENT_ID',
    CLEAR_DISADVANTAGE_CONTENT_ID: 'CLEAR_DISADVANTAGE_CONTENT_ID',
};
