
const itemmm=[
    { id:0,parentId:null, startDate: '2022.04.19',  country: 'AB', activity: 'marketing', marketingActivity: 'Presentation', businessUnıte: 'Alpha', ar: 2, zoneId: 1, position: 'AM', employee: 'Ali Ömer', parcent: 21, product: 'TT', yuzde: 70, specilization: 1,indication:2, progress: 3, current: 25, clinic: 6, costStatus: 'Not Planned', planed: '1.2000.00', actual: '-', last3: '1.150,00', next3: '1.750,00', cur:'USD', res: '52%', actualz: 'planned', report: '2 types of wiew', question: 'Complited'       ,buttons:[<button><i className="fa-solid fa-person-running"></i></button>,
    <button><i className="fa-solid fa-calculator"></i></button>,
    <button><i class="fa-solid fa-hand-holding-dollar"></i></button>,
    <button><i class="fa-solid fa-star"></i></button>,
    <button><i class="fa-solid fa-file-invoice-dollar"></i></button>,
    <button><i class="fa-solid fa-users-between-lines"></i></button>,]},
    { id:1,parentId:0, startDate: '2022.05.19',  country: 'CD', activity: 'marketing', marketingActivity: 'Seminer', businessUnıte: 'Beta', ar: 6, zoneId: 10, position: 'AM', employee: 'Ali Ömer', parcent: 140, product: 'AL , TT', yuzde: 60, specilization: 16,indication:3, progress: 12, current: 55, clinic: 'YILDIZ', costStatus: 'Planned', planed: '-', actual: '1.000,00', last3: '1.150,00', next3: '1.750,00', cur:'USD', res: '52%', actualz: 'Request', report: '2 types of wiew', question: 'auto Plan'    ,buttons:[<button><i className="fa-solid fa-person-running"></i></button>,
    <button><i className="fa-solid fa-calculator"></i></button>,
    <button><i class="fa-solid fa-hand-holding-dollar"></i></button>,
    <button><i class="fa-solid fa-star"></i></button>,
    <button><i class="fa-solid fa-file-invoice-dollar"></i></button>,
    <button><i class="fa-solid fa-users-between-lines"></i></button>,]},
    { id:2,parentId:0, startDate: '2022.06.19',  country: 'EF', activity: 'marketing', marketingActivity: 'Congress', businessUnıte: 'Beta', ar: 11, zoneId: 12, position: 'AM', employee: 'Ali Ömer', parcent: 33, product: 'PRF', yuzde: 100, specilization: 11,indication:11, progress: 17, current: 63, clinic: 3, costStatus: 'Planned', planed: '1.2000,00', actual: '1.000,00', last3: '1.150,00', next3: '1.750,00',cur:'USD', res: '52%', actualz: 'Financial', report: '2 types of wiew', question: 'auto Plan' ,buttons:[<button><i className="fa-solid fa-person-running"></i></button>,
    <button><i className="fa-solid fa-calculator"></i></button>,
    <button><i class="fa-solid fa-hand-holding-dollar"></i></button>,
    <button><i class="fa-solid fa-star"></i></button>,
    <button><i class="fa-solid fa-file-invoice-dollar"></i></button>,
    <button><i class="fa-solid fa-users-between-lines"></i></button>,]},
    { id:4,parentId:null, startDate: '2022.05.19',  country: 'CD', activity: 'marketing', marketingActivity: 'Seminer', businessUnıte: 'Beta', ar: 6, zoneId: 10, position: 'AM', employee: 'Ali Ömer', parcent: 140, product: 'AL , TT', yuzde: 60, specilization: 16,indication:3, progress: 12, current: 55, clinic: 'YILDIZ', costStatus: 'Planned', planed: '-', actual: '1.000,00', last3: '1.150,00', next3: '1.750,00', cur:'USD', res: '52%', actualz: 'Request', report: '2 types of wiew', question: 'auto Plan'    ,buttons:[<button><i className="fa-solid fa-person-running"></i></button>,
    <button><i className="fa-solid fa-calculator"></i></button>,
    <button><i class="fa-solid fa-hand-holding-dollar"></i></button>,
    <button><i class="fa-solid fa-star"></i></button>,
    <button><i class="fa-solid fa-file-invoice-dollar"></i></button>,
    <button><i class="fa-solid fa-users-between-lines"></i></button>,]},
    { id:3,parentId:4, startDate: '2022.04.19',  country: 'AB', activity: 'marketing', marketingActivity: 'Presentation', businessUnıte: 'Alpha', ar: 2, zoneId: 1, position: 'AM', employee: 'Ali Ömer', parcent: 21, product: 'TT', yuzde: 70, specilization: 1,indication:2, progress: 3, current: 25, clinic: 6, costStatus: 'Not Planned', planed: '1.2000.00', actual: '-', last3: '1.150,00', next3: '1.750,00', cur:'USD', res: '52%', actualz: 'planned', report: '2 types of wiew', question: 'Complited'       ,buttons:[<button><i className="fa-solid fa-person-running"></i></button>,
    <button><i className="fa-solid fa-calculator"></i></button>,
    <button><i class="fa-solid fa-hand-holding-dollar"></i></button>,
    <button><i class="fa-solid fa-star"></i></button>,
    <button><i class="fa-solid fa-file-invoice-dollar"></i></button>,
    <button><i class="fa-solid fa-users-between-lines"></i></button>,]},
    { id:5,parentId:3, startDate: '2022.06.19',  country: 'EF', activity: 'marketing', marketingActivity: 'Congress', businessUnıte: 'Beta', ar: 11, zoneId: 12, position: 'AM', employee: 'Ali Ömer', parcent: 33, product: 'PRF', yuzde: 100, specilization: 11,indication:11, progress: 17, current: 63, clinic: 3, costStatus: 'Planned', planed: '1.2000,00', actual: '1.000,00', last3: '1.150,00', next3: '1.750,00',cur:'USD', res: '52%', actualz: 'Financial', report: '2 types of wiew', question: 'auto Plan' ,buttons:[<button><i className="fa-solid fa-person-running"></i></button>,
    <button><i className="fa-solid fa-calculator"></i></button>,
    <button><i class="fa-solid fa-hand-holding-dollar"></i></button>,
    <button><i class="fa-solid fa-star"></i></button>,
    <button><i class="fa-solid fa-file-invoice-dollar"></i></button>,
    <button><i class="fa-solid fa-users-between-lines"></i></button>,]},
    { id:6,parentId:3, startDate: '2022.06.19',  country: 'EF', activity: 'marketing', marketingActivity: 'Congress', businessUnıte: 'Beta', ar: 11, zoneId: 12, position: 'AM', employee: 'Ali Ömer', parcent: 33, product: 'PRF', yuzde: 100, specilization: 11,indication:11, progress: 17, current: 63, clinic: 3, costStatus: 'Planned', planed: '1.2000,00', actual: '1.000,00', last3: '1.150,00', next3: '1.750,00',cur:'USD', res: '52%', actualz: 'Financial', report: '2 types of wiew', question: 'auto Plan' ,buttons:[<button><i className="fa-solid fa-person-running"></i></button>,
    <button><i className="fa-solid fa-calculator"></i></button>,
    <button><i class="fa-solid fa-hand-holding-dollar"></i></button>,
    <button><i class="fa-solid fa-star"></i></button>,
    <button><i class="fa-solid fa-file-invoice-dollar"></i></button>,
    <button><i class="fa-solid fa-users-between-lines"></i></button>,]}
  ]
  
export function generateRows() {
  return itemmm;
}

