export const EditEventTypes = {
    PLANNED_VISIT: "PLANNET_VISID",
    VISIT_EVULOTİON_PROMO: "VISIT_EVULOTİON_PROMO",
    VISIT_EVULOTİON_NON_PROMO: "VISIT_EVULOTİON_NON_PROMO",
    VISIT_EVULOTİON_OTHER: "VISIT_EVULOTİON_OTHER",
    NUMBER_OF_PATTIENS: "NUMBER_OF_PATTIENS",
    PHARMACY_SPLIT_DATA : 'PHARMACY_SPLIT_DATA'
}