export const TaskManagementActionTypes = {
    RECURRENCE_DATA: 'RECURRENCE_DATA',
    PARENT_PROCESS_ID: 'PARENT_PROCESS_ID',
    RECURRENCE_TYPE: 'RECURRENCE_TYPE',
    CLEAN_UP_RECURRENCE_DATA: 'CLEAN_UP_RECURRENCE_DATA',
    NEW_SUB_PROCESS_ID: 'NEW_SUB_PROCESS_ID',
    OLD_SUB_PROCESS_ID: 'OLD_SUB_PROCESS_ID',
    FILTER_SHOW: 'FILTER_SHOW',
    RECURRENCE_UPDATE_DATA: 'RECURRENCE_UPDATE_DATA',
};
