export const VisitMixActionTypes={
    VM_GET_YEARS:"VM_GET_YEARS",
    VM_SET_YEARS:"VM_SET_YEARS",
    VM_GET_COUNTRY:"VM_GET_COUNTRY",
    VM_SET_COUNTRY:"VM_SET_COUNTRY",
    VM_GET_BUS_UNIT:"VM_GET_BUS_UNIT",
    VM_SET_BUS_UNIT:"VM_SET_BUS_UNIT",
    VM_GET_CALENDAR_DATA:"VM_GET_CALENDAR_DATA",
    VM_GET_CALENDAR_DATA_BODY:"VM_GET_CALENDAR_DATA_BODY",
    USER_INFO:"USER_INFO",
    VM_SET_CALENDAR_DATA_BUTTON:"VM_SET_CALENDAR_DATA_BUTTON",
    VM_GET_CALENDAR_DATA_BUTTON:"VM_GET_CALENDAR_DATA_BUTTON",
    VM_CALENDAR_PRODUCT:"VM_CALENDAR_PRODUCT"
}