export const NeedsType ={
    NEEDSTAB :  'NEEDSTAB',
    NEEDPAGE_BUTTON_DATAS : 'NEEDPAGE_BUTTON_DATAS',
    BENEFITTAB:'BENEFITTAB',
    BENEFIT_BUTTON_DATAS : 'BENEFIT_BUTTON_DATAS',
    DISADVANTAGE_BUTTON_DATAS : 'DISADVANTAGE_BUTTON_DATAS',
    DISADVANTAGE_TAB: 'DISADVANTAGE_TAB',
    PAGE_LIST_PLUS: 'PAGE_LIST_PLUS',
    FILTER: 'FILTER'
}