export const VisitContentTypes = {
    ITEM_ID: 'ITEM_ID',
    RESET_ITEM_ID: 'RESET_ITEM_ID',
    ITEM_NAME: 'ITEM_NAME',
    RESET_ITEM_NAME: 'RESET_ITEM_NAME',
    TEMPLATE_ID: 'TEMPLATE_ID',
    RESET_TEMPLATE_ID: 'RESET_TEMPLATE_ID',
    IS_PAGE: 'IS_PAGE',
};
